Repository QuEraComputing/bloqade-shuttle, pull requests merged in 2025-08, with the labels that each got.

#51 updated MSD example (new comment formatting)
  docs/blog/posts/MSD_moves.md
Labels: documentation

#58 Bug Fixes.
  src/bloqade/shuttle/arch.py
  src/bloqade/shuttle/passes/fold.py
  test/unit/test_arch.py
Labels: bug

#63 Updating the pathing for Two col single zone layout.
  src/bloqade/shuttle/stdlib/layouts/two_col_zone.py
Labels: backport 0.7
